
| Class name   |  Precision %  |    Recall %  |     AP %    |
|:-------------|:-------------:|:------------:|:-----------:|
| person       |      100      |     4.9      |     9.8     |
| fall         |     93.8      |     20.4     |    35.2     |

Averages over classes %:
-----------------------
 Mean precision: 96.9
 Mean recall:    12.7
 Mean AP (mAP):  22.5

Plotting precision versus recall curves
Plots directory: Y:\VM\stm-workspace\stm32ai-modelzoo-services\object_detection\src\experiments_outputs\2025_05_21_10_39_55\precision_vs_recall_curves\quantized_model.tflite
[INFO] : Establishing a connection to STM32Cube.AI Developer Cloud to launch the model benchmark on STM32 target...
[INFO] : Successfully connected!
[INFO] : Starting the model benchmark on target STM32N6570-DK, other available boards ['STM32MP157F-DK2', 'STM32MP135F-DK', 'STM32MP257F-EV1', 'STM32F469I-DISCO', 'STM32L4R9I-DISCO', 'STM32N6570-DK', 'STM32H573I-DK', 'STM32H7B3I-DK', 'STM32H7S78-DK', 'NUCLEO-F401RE', 'NUCLEO-G474RE', 'B-U585I-IOT02A', 'NUCLEO-H743ZI2', 'STM32F769I-DISCO', 'STM32H735G-DK', 'STM32H747I-DISCO', 'ISM330IS', 'LSM6DSO16IS', 'STM32F746G-DISCO', 'SR5E1-EVBE3000D', 'SR6PX-EVBC4000P']...
[INFO] : Total RAM : 1643.23 (KiB)
[INFO] :     RAM Activations : 1641.5 (KiB)
[INFO] :     RAM Runtime : 1.73 (KiB)
[INFO] : Total Flash : 2197.51 (KiB)
[INFO] :     Flash Weights  : 1640.2 (KiB)
[INFO] :     Estimated Flash Code : 557.31 (KiB)
[INFO] : MACCs : 0.0 (M)
[INFO] : Internal RAM usage : 1641.5 (KiB)
[INFO] : External RAM usage : 0.0 (KiB)
[INFO] : Number of cycles : 17.074 (M)
[INFO] : Inference Time : 21.34 (ms)




general:
  project_name: E-FPDS-Dataset
  model_type: ssd_mobilenet_v2_fpnlite
#choices=[st_ssd_mobilenet_v1, ssd_mobilenet_v2_fpnlite, tiny_yolo_v2, st_yolo_lc_v1, 
#         st_yolo_x, yolo_v8, yolo_v5u]
  model_path: #Y:/VM/stm-workspace/stm32ai-modelzoo-services/object_detection/src/experiments_outputs/2025_05_10_12_08_02/quantized_models/quantized_model.tflite
  logs_dir: logs
  saved_models_dir: saved_models
  gpu_memory_limit: 15
  num_threads_tflite: 12
  global_seed: 127

operation_mode: chain_tqeb
#choices=['training' , 'evaluation', 'deployment', 'quantization', 'benchmarking',
#        'chain_tqeb','chain_tqe','chain_eqe','chain_qb','chain_eqeb','chain_qd ']

dataset:
  name: E-FPDS-Dataset
  class_names: [ person, fall ]
  training_path: ../datasets/E-FPDS-Dataset/train
  validation_path: ../datasets/E-FPDS-Dataset/valid
  validation_split: 0.15
  test_path: ../datasets/E-FPDS-Dataset/test
  quantization_path: ../datasets/E-FPDS-Dataset/valid
  quantization_split: 0.3
  seed: 123 

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: rgb
  
data_augmentation:
  random_contrast:
    factor: 0.4
  random_brightness:
    factor: 0.3
  random_flip:
    mode: horizontal
  random_translation:
    width_factor: 0.1
    height_factor: 0.1
  random_rotation:
    factor: 0.05

training:
  model:
    alpha: 0.35
    input_shape: (256, 256, 3) #(192, 192, 3)
    pretrained_weights: imagenet
  dropout:
  batch_size: 64
  epochs: 1000
  optimizer:
    Adam:
      learning_rate: 0.001
  callbacks:
    ReduceLROnPlateau:
      monitor: val_loss
      patience: 20
    EarlyStopping:
      monitor: val_loss
      patience: 40


postprocessing:
  confidence_thresh: 0.6
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.3
  plot_metrics: True   # Plot precision versus recall curves. Default is False.
  max_detection_boxes: 10

quantization:
   quantizer: TFlite_converter
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float
   export_dir: quantized_models

benchmarking:
  board: STM32N6570-DK

tools:
  stedgeai:
    version: 10.0.0
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: C:/ST/STEdgeAI/2.1/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.18.0/STM32CubeIDE/stm32cubeide.exe

deployment:
  c_project_path: ../../application_code/object_detection/STM32N6/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32N6
    board: STM32N6570-DK

mlflow:
  uri: ./experiments_outputs/mlruns

hydra:
  run:
    dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
    